[package]
name = "ex"
version = "0.1.0"
edition = "2021"
default-run = "ex"

[dependencies]
eframe = {path = "../../egui/eframe"}
ex_core = { path = "../ex_core" }
egui_extras = {path = "../../egui/egui_extras"}
