[package]
name = "ex"
version = "0.1.0"
edition = "2021"
default-run = "ex"

[dependencies]
eframe = {path = "../../egui/eframe"}
egui_extras = {path = "../../egui/egui_extras"}
jwalk = "0.6.0"
open = "2.1.2"
trash = "2.1.0"
chrono = "0.4.19"